# Copyright (c) CloudBees, Inc.

name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "📚 Documentation"
    label: "documentation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Versions
  [![Helm Chart](https://img.shields.io/badge/Chart-xxxxx-informational?style=flat-square)](https://artifacthub.io/packages/helm/cloudbees/cloudbees-core)
  [![Application](https://img.shields.io/badge/App-xxxxx-informational?style=flat-square)](https://docs.cloudbees.com/docs/release-notes/latest/cloudbees-ci)
  [![K8s](https://img.shields.io/badge/K8s-xxxxx-informational?style=flat-square)](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

  ## Changes

  $CHANGES
