# Copyright (c) CloudBees, Inc.

name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "📚 Documentation"
    label: "documentation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Versions

  * [CloudBees CI Helm Chart version](https://artifacthub.io/packages/helm/cloudbees/cloudbees-core): ![](https://img.shields.io/badge/Version-xxxxx-informational?style=flat-square)
  * [CloudBees CI Release Notes](https://docs.cloudbees.com/docs/release-notes/latest/cloudbees-ci): ![](https://img.shields.io/badge/Version-xxxxx-informational?style=flat-square)
  * [Kubernetes version](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html): ![](https://img.shields.io/badge/Version-xxxxx-informational?style=flat-square)

  ## Changes

  $CHANGES
