# Copyright (c) CloudBees, Inc.

#https://artifacthub.io/packages/helm/cloudbees/cloudbees-core/
#https://docs.cloudbees.com/docs/cloudbees-ci/latest/eks-install-guide/installing-eks-using-helm

OperationsCenter:
  Ingress:
    Annotations:
      alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true
  NodeSelector:
    ci_type: cb-apps
  Tolerations:
    - key: dedicated
      operator: Equal
      value: cb-apps
      effect: NoSchedule
  CasC:
    Enabled: true
    Retriever:
      Enabled: true
      scmRepo: https://github.com/cloudbees/casc-cloudbees-ci-eks-addon.git
      scmBranch: main
      scmBundlePath: bp02.oc
      scmPollingInterval: PT20M
Persistence:
  StorageClass: efs
Hibernation:
  Enabled: true
Agents:
  SeparateNamespace:
    Enabled: true
    Create: true
    Name: cbci-agents
