# Copyright (c) CloudBees, Inc.

#https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "cjoc"
        metrics_path: "/prometheus/"
        static_configs:
          - targets: ["cjoc.cbci.svc.cluster.local:80"]
    serviceMonitorSelector:
      # Note: For all Service Monitors, use a common label
      matchLabels:
        release: kube-prometheus-stack
additionalPrometheusRulesMap:
  rule-name:
    groups:
      - name: Controllers
        rules:
          - alert: JenkinsTooManyPluginsNeedUpate
            expr: sum(jenkins_plugins_withUpdate) by (pod) > 3
            for: 1m
            labels:
              severity: notify
            annotations:
              summary: " {{ $labels.pod }} too many plugins updates"
              description: " {{ $labels.pod }} has {{ $value }} plugins that require an update"
      - name: Builds
        rules:
          - alert: JenkinsTooManyJobsQueued
            expr: sum(jenkins_queue_size_value) > 5
            for: 1m
            labels:
              severity: notify
            annotations:
              summary: " {{ $labels.pod }} too many jobs queued"
              description: "{{ $labels.pod}} has {{ $value }} jobs stuck in the queue"
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: ${cert_arn}
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      external-dns.alpha.kubernetes.io/hostname: ${grafana_hostname}
    hosts:
      - ${grafana_hostname}
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "grafana-dashboards-cloudbees"
          orgId: 1
          folder: "CloudBees"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/grafana-dashboards-cloudbees
  dashboards:
    grafana-dashboards-cloudbees:
      cb-controllers:
        url: https://raw.githubusercontent.com/cloudbees/terraform-aws-cloudbees-ci-eks-addon/main/blueprints/02-at-scale/k8s/kube-prom-stack-grafana-db.json
        token: ""
