# Copyright (c) CloudBees, Inc.

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-cbci
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cbci
  selector:
    matchLabels:
      "cloudbees.prometheus": "true"
  endpoints:
    - port: http
      interval: 30s
      path: /prometheus/
