# Default values for osixia-openldap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

openldap:
  # -- Image for OpenLDAP with mock data
  image: "carlosrodlop/ooldap.debian:latest"