apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: agent

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
    - name: Checkout code
      uses: cloudbees-io/checkout@v1
    - name: Maven Build
      uses: docker://maven:3-openjdk-11
      shell: sh
      run: |
       ls -la

