apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ci

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
    - name: Checkout code
      uses: cloudbees-io/checkout@v1

    - name: Configure AWS Credentials
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.tfawscb_aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.tfawscb_aws_secret_access_key }}

    - name: Blueprints 01-getting-started
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/terraform-aws-cloudbees-ci-eks-addon:latest
      run : |
        cat <<EOT >> blueprints/greetings.txt
        tags = {
          "cb-owner" : "professional-services"
          "cb-user" : "crodriguezlopez"
          "cb-purpose" : "demo"
        }
        hosted_zone = "bp.core.pscbdemos.com"
        temp_license = {
          first_name  = "Carlos"
          last_name  = "Lopez"
          email = "crodriguezlopez@cloudbees.com"
          company = "CloudBees Inc."
        }
        EOT
        cat blueprints/greetings.txt
