# Copyright (c) CloudBees, Inc.

apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: agent

#TODO: Replace by pull_request when it is supported
on:
  push:
    branches:
      - '**'

env:
  REGISTRY: public.ecr.aws/r1n1q0e5
  AGENT_NAME: cloudbees-labs/tf-aws-cb-ci-eks-addon-agent
  OPENLDAP_NAME: cloudbees-labs/tf-aws-cb-ci-eks-addon-ldap
  VERSION: latest
  AWS_REGION: us-east-1

jobs:
  build:
    steps:
    - name: Checkout code
      uses: cloudbees-io/checkout@v1

    - name: Configure AWS Credentials
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_TF_CBCI_EKS_AccessKeyID }}
        aws-secret-access-key: ${{ secrets.AWS_TF_CBCI_EKS_SecretAccessKey }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: cloudbees-io/configure-ecr-credentials@v1

    #TODO: Replace by rootless image when it is supported
    - name: Build, tag, and push Agent docker image to CloudBees PS Amazon ECR
      uses: cloudbees-io/kaniko@v1
      with:
        dockerfile: .docker/agent/Dockerfile.root
        context: .
        destination: ${{ env.REGISTRY }}/${{ env.AGENT_NAME }}:${{ env.APP_VERSION }}

    - name: Build, tag, and push Openldap docker image to CloudBees PS Amazon ECR
      uses: cloudbees-io/kaniko@v1
      with:
        dockerfile: .docker/openldap/Dockerfile.root
        context: .
        destination: ${{ env.REGISTRY }}/${{ env.OPENLDAP_NAME }}:${{ env.APP_VERSION }}